### ISSUE TITLE
Создать модель для компаний

### ISSUE THREAD

**Issue by TyVik** [krddevdays/backend#103]
Для вакансий потребовалась отдельная модель компаний, которая также может быть переиспользована в других местах.

Поля:
- название компании;
- описание компании;
- адрес (опционально);
- координаты для адреса (опционально);
- сайт компании (опционально);
- телефон (опционально);
- email (опционально);
- линк на пользователя-администратора;
- статус ACTIVE/HIDDEN.

**Comment by langovoi** [comment]
Сайт компании (опционально)
Телефон (опционально)
E-mail (опционально)

**Comment by langovoi** [comment]
Адрес и координаты опциональные — вдруг это удаленная компания, которая решила просто вакансию разместить (таких мы в каталоге компаний не будем показывать, в каталоге нас интересуют только компании с офисом в Краснодаре)

**Comment by langovoi** [comment]
Название, описание и пользователь-администратор — обязательные. Это программа минимум для создания вакансии.

**Comment by langovoi** [comment]
Хотелось бы сразу сделать права доступа к компании, но в целом можно опустить на первом этапе.
Под правами доступа я подразумеваю что какие-то пользователи, которым администратор компании выдал доступ, могут совершать действия: публиковать вакансии, редактирование описание. Права должны быть гранулярны (например один пользователь может публиковать вакансии, другой нет).

**Comment by langovoi** [comment]
Администратор может передать свои права администратора компании другому пользователю

**Comment by langovoi** [comment]
Должен быть статус компании. Чтобы мы, админы, могли в случае чего скрыть компанию, но не удалять.
Думаю пока два статуса хватит: `ACTIVE`, `HIDDEN`.
По умолчанию `ACTIVE`, но из админка можно установить `HIDDEN`.

**Comment by TyVik** [comment]
Как насчёт логотипа компании?

**Comment by langovoi** [comment]
> Как насчёт логотипа компании?

Я думал об этом, но кажется это лишнее на первом этапе. Мы еще не представляем какие у нас технические требования для логотипа будут (размер). Можно добавить позже.

**Comment by langovoi** [comment]
Можно ещё добавить размер компании, enum. (подсмотрел у Хабр Карьеер)
<img width="595" alt="image" src="https://user-images.githubusercontent.com/5055595/95013327-4336aa00-0648-11eb-8c07-a17186afdb35.png">

**Comment by TyVik** [comment]
ok, давай тогда с правами тоже позже определимся? Я пока не могу представить скоуп прав и взаимодействия между ними.

**Comment by langovoi** [comment]
> ok, давай тогда с правами тоже позже определимся? Я пока не могу представить скоуп прав и взаимодействия между ними.

Да, без проблем. Я там как раз ремарку оставил, что это сейчас не критично, но нужно не забыть.
