### ISSUE TITLE
Сущность Доклад

### ISSUE THREAD

**Issue by langovoi** [krddevdays/backend#15]
Базовая информация о докладе это название и Автор.
Автор - имя, фамилия и опционально фото, компания и должность.

**Comment by langovoi** [comment]
Так же у докладов должна быть классификация.
Предлагаю сейчас это реализовать с помощью тегов.

**Comment by langovoi** [comment]
У доклада может быть Презентация.
Презентация состоит из двух полей: тип и ссылка.
Тип пока что может быть pdf, html.

**Comment by langovoi** [comment]
Так же у Доклада может быть видео записи.
Предлагаю еще хранить так же как Презентацию: тип и ссылка.
Тип пока что только YouTube.

**Comment by langovoi** [comment]
Автор доклада может быть пользователем нашего портала. Тут стоит подумать как это лучше сделать.

**Comment by binakot** [comment]
Доклад и спикер это две отдельные сущности. У одного автора может быть несколько докладов, к тому же бывают парные доклады: один доклад с двумя спикерами (а может и больше, но я такого не видел).

Из свойств, которые приходят в голову.

Доклад:
* Название
* Описание (тезисы, анонс, etc)
* Тематика (теги) - аналогия как у Онтико, может быть много
* Сложность - уровень хардкорности
* Презентация - ссылка на слайды (возможно, стоит поддерживать множество ссылок, чтобы можно было указать несколько файлов, например, в разных форматах)
* Запись доклада - ссылка на видеозапись, когда доклад уже прошел (возможно, стоит также поддерживать несколько ссылок на разные ресурсы)

Спикер:
* Имя (можно одним полем ФИО, можно разнести на отдельные, тут стоит подумать)
* Должность
* Компания
* Фото
* Контакты (возможно, спикер захочет оставить свой твиттер или еще что-то. В целом это поле можно сделать просто более общим и назвать "О спикере" или что-то типа того)

Еще доклад относиться к какому-то конкретному событию, а также имеет время и место (для событий в несколько треков с отдельными залами) выступления. 

Интересный момент, если докладчик выступает несколько раз с одним и тем же докладов, наверное, такое можно игнорировать на данном этапе и просто считать это разными докладами.

**Comment by TyVik** [comment]
Итого структура:
Спикер:
- Имя
- Фамилия
- Компания (nullable)
- Должность (nullable)

Доклад:
- Название
- Описание
- Спикер (fk)
- Классификация (m2m, nullable)
- Презентация (поле для URL, nullable)
- Видео (поле для URL, nullable)

Это то, что можно сделать относительно быстро. Подключение стораджа и хранение презентаций там может занять больше дня. Остальные поля пока не используются, так что и смысла их пока вводить не вижу.

**Comment by langovoi** [comment]
Для презентации стоит добавить тип, потому что как минимум сейчас они бывают в pdf и бывают web версии, но во всех вариантах ссылка.

Для спикера все же нужно добавить ссылку на аватарку.

Никаких хранений файлов на стороне Django пока не делаем, я буду сам ручками заливать куда-нибудь, прописывать ссылку и наверно просто подниму [imgproxy](https://github.com/imgproxy/imgproxy) чтобы использовать его на фронте.

**Comment by langovoi** [comment]
Мыслей как опционально связать спикера с пользователем я так понимаю нет?

**Comment by TyVik** [comment]
Давай я добавлю 2 поля для презентаций: на pdf и на online? Если человек делает презентацию в гуглослайдах, то ему нужен также фолбек и на оффлайн версию. Т.е. 2 поля будут заполнены одновременно.

**Comment by TyVik** [comment]
В каком месте будет использоваться аватарка спикера? Я пока думал лишь у доклада делать постеры.

**Comment by TyVik** [comment]
А где мы будем классификацию использовать? Имеет ли смысл её делать именно сейчас?

**Comment by langovoi** [comment]
Классификация будет на странице доклада, возможно ещё на карточке + фильтр на поиск по докладам.

Аватарка спикера будет на карточке доклада, на странице доклада и докладчика. Постера доклада пока не будет, это уже другая штука, которую нужно ещё придумать как реализовать.

По презентации - ок

**Comment by TyVik** [comment]
Давай классификацию вынесем в отдельную фичу? Её раньше не было, и пока она не критична.

Я всё-таки настаиваю на постере делала как минимум. Аватарку спикер моет менять, а вот постер должен сохранятся. Аватарку для спикера сделаю.

**Comment by langovoi** [comment]
Окей - классификацию выносим на потом.

Какой постер? Он нигде не будет отображаться на сайте, а вот аватарка будет.

**Comment by TyVik** [comment]
Ладно, вам виднее - без постера, с аватаркой.
