### ISSUE TITLE
Информация по подаче докладов на событие

### ISSUE THREAD

**Issue by langovoi** [krddevdays/backend#34]
Добавляем для события две опциональные даты начала и конца приема докладов (`cfp_start`, `cfp_finish`).
Если хотя бы одна из дат введена требуем ввести ссылку на форму для подачи докладов (`cfp_url`)

Отдаем эти данные в API.

**Comment by TyVik** [comment]
https://github.com/krddevdays/backend/commit/1b4771451490b142efb5d26f318476855977be8e
Косякнул с тегом в заголовке коммита.
