### ISSUE TITLE
Круглые столы

### ISSUE THREAD

**Issue by langovoi** [krddevdays/backend#37]
Круглые столы подают пользователи на конкретное событие.
Другие пользователи могут голосовать за круглые столы.

У события должны быть временные ограничения на подачу тем на круглый стол (опциональные);

Потом мы будем закреплять круглые столы к активностям, поэтому нужно добавить новый тип активности – `ROUND_TABLE`.

Модель:
1) title;
2) description;
3) author_id;
4) activity_id, опционально;
5) votes, вычисляемое поле с количеством голосов.

Голоса думаю стоит хранить как отдельную сущность из следующих полей:
1) round_table_id;
2) user_id;

Голосовать за свой круглый стол нельзя;
Голосовать дважды нельзя;

Делаем следующие API:
1) список круглых столов для события;
2) подача своей темы круглого стола (только для авторизованных).

**Comment by TyVik** [comment]
1. Я бы по-другому назвал тип активности, например `DISCUSSION`. `ROUND_TABLE` звучит как калька с русского.

2. Временные ограничения предлагаю ввести позже, они вроде бы терпят до августа.

3. Согласен, список проголосовавших - в M2M таблице. Там и дважды голосовать не получится.

4. Ещё одно поле надо - привязка к `Event`, т.к. `Activity` может быть пустым.

5. `Голосовать за свой круглый стол нельзя;` - может, всё-таки "Особые случаи не настолько особые, чтобы нарушать правила"? Ну что там 1 голос...
==========================
Думаю, с моделями проблем не возникнет, можно начинать. А после них и API обсудим.

**Comment by TyVik** [comment]
https://github.com/krddevdays/backend/pull/51
