### ISSUE TITLE
Привязка доклада к событию в обход активности

### ISSUE THREAD

**Issue by langovoi** [krddevdays/backend#38]
Во время подготовки мероприятия доклад уже может быть анонсирован на конкретное событие, но для него не выбран слот в расписание (нет связи с активность). 

Делаем API для получения списка докладов события.

**Comment by TyVik** [comment]
Добавил связь доклада с событием, пробросил в API как поле `event_id` в сериализаторе доклада. Обращаться можно по урлу `/talks/?event_id=<id>` (в тестах есть). 

Я намеренно не хочу делать на первый взгляд более логичный урл `/events/<id>/talks/`, т.к. хочу держать держать события и доклады раздельно. Это позволит работать с докладами как с отдельной сущностью в дальнейшем при реализации воркфлоу. Пиши, если нужны ещё какие-нибудь фильтры/флаги/поиск...

**Comment by langovoi** [comment]
Понял, вроде вполне логично.
