### ISSUE TITLE
Сортировка для зон внутри площадок

### ISSUE THREAD

**Issue by langovoi** [krddevdays/backend#40]
Есть проблема с тем, что нужно отображать зоны в расписание в определенном порядке.
Думаю стоит сделать возможность указывать порядок для зон внутри площадки.

Эти данные нужно отдавать в API события, думаю можно внутри `venue`

**Comment by TyVik** [comment]
Добавлю поле `order` в модель `Zone` и подключу в выдачу API.

**Comment by TyVik** [comment]
Так, order-то я добавил, а куда в API выводить?

**Comment by TyVik** [comment]
https://github.com/krddevdays/backend/pull/42

**Comment by langovoi** [comment]
> Так, order-то я добавил, а куда в API выводить?

В запросе события добавить внутри `venue` массив `zones` со словарями внутри которых `name` И `order`. Так удобно будет?

**Comment by TyVik** [comment]
Добавил.
