### ISSUE TITLE
Поле должность и место работы у участников конференции

### ISSUE THREAD

**Issue by binakot** [krddevdays/backend#54]
На бейджах хочется видеть, где работает человек и кем :)
Лично мне уже пару раз вопрос задавали, почему при покупке билетов не спрашивают эту инфу.

**Comment by langovoi** [comment]
@TyVik сделает завтра в рамках API для профиля.

**Comment by TyVik** [comment]
Добавлено в https://github.com/krddevdays/backend/pull/61
