### ISSUE TITLE
Статус событий

### ISSUE THREAD

**Issue by langovoi** [krddevdays/backend#80]
Нужно сделать статусы для событий:
1) `draft` (приходит в API только тем, у кого есть специальный permission или superuser status)
1) `published` (приходит всем)

Всем текущим событиям проставляем `published`

**Comment by sergeibershadsky** [comment]
Похоже что одного признака published достаточно чтобы отвечать обоим задачам

**Comment by langovoi** [comment]
В дальнейшем могут будут другие статусы + нужна индикация для фронта (чтобы визуально разделять `draft` и `published`).

Также в зависимости от статуса нужно будет делать некоторые поля опциональными, вместо обязательных (чуть позже)

**Comment by binakot** [comment]
Ну да, как минимум, можно добавить еще `canceled`, если вдруг ивент отменили.
