### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by TyVik** [krddevdays/backend#81]
Предлагаю добавить на сайт правила поведения.

The Krasnodar Dev Days community is made up of members from around the Krasnodar and other cities with a diverse set of skills, personalities, and experiences. It is through these differences that our community experiences great successes and continued growth. When you're working with members of the community, we encourage you to follow these guidelines which help steer our interactions and strive to keep Krasnodar Dev Days a positive, successful, and growing community.

A member of the Krasnodar Dev Days community is:

Open
Members of the community are open to collaboration, feel free to ask questions. We're receptive to constructive discussion and useful criticism. We're accepting of all who wish to take part in our activities, discussions, workshops, fostering an environment where anyone can participate and everyone can make a difference.

Considerate
Members of the community are considerate of their peers -- other members. We take into account and respect the opinions of other people. In discussions, we are guided by facts and common sense, without moving on to emotions. Only positively colored, emotional messages are allowed in our community. We're tactful when approaching differing views.

Respectful
Members of the community are respectful. We're respectful of others, their positions, their skills, their commitments, and their efforts. When we disagree, we are courteous in raising our issues.

Overall, we're good to each other. We contribute to this community not because we have to, but because we want to. We want to share the knowledge, advice novice, ask for questions, grow yourself with the community and make yourself better. 

Questions/comments/reports? Please write to admin@krddevdays.org.

**Comment by binakot** [comment]
А русский вариант будет?

**Comment by TyVik** [comment]
Ну как-то так:

Сообщество Krasnodar Dev Days состоит из жителей Краснодара и других городов с различными навыками, личностями и опытом. Именно благодаря этим качествам наше сообщество гостеприимно, открыто для всех и постоянно растёт. Мы рекомендуем вам следовать этим рекомендациям, когда вы общаетесь с членами сообщества. Они призваны помогать нам лучше взаимодействовать, и стремиться к тому, чтобы Krasnodar Dev Days были позитивным, успешным и растущим сообществом.

Каждый из сообщества Krasnodar Dev Days:

Открыт
Члены сообщества открыты для сотрудничества, не стесняйтесь задавать вопросы. Мы понимаем только конструктивное обсуждение и полезную критику. Мы принимаем всех, кто желает принять участие в наших мероприятиях, дискуссиях, семинарах, а также создании среды, в которой каждый может участвовать, и каждый может внести свой вклад.

Тактичен
Члены сообщества внимательны к окружающим - другим членам. Мы учитываем и уважаем мнение других людей. В дискуссиях мы руководствуемся фактами и здравым смыслом, не переходя на эмоции. Только позитивно окрашенные, эмоциональные сообщения разрешены в нашем сообществе. Мы тактичны к любой иной точке зрения, пусть даже она не соответствует нашей.

Почтителен
Члены сообщества уважительны. Мы уважаем других, их позиции, их навыки, их обязательства и их усилия. Когда мы не согласны, мы вежливо задаём наши вопросы.

В общем, у нас здорово! Мы вносим свой вклад в это сообщество не потому, что должны, а потому, что хотим. Мы хотим делиться знаниями, советовать новичкам, задавать вопросы сами, расти вместе с сообществом и становиться лучше.

Вопросы / комментарии / отчеты? Пожалуйста, пишите на admin@krddevdays.org.

**Comment by neonick** [comment]
Давайте возьмём какой-нибудь готовый? типа такого https://pitercss.com/code-of-conduct-ru

**Comment by TyVik** [comment]
Я взял CoC Python сообщества и немного его адаптировал. Ссылку на оригинал приложить не могу, т.к. они его изменили 24 сентября. Но я не против взять и готовый. Желательно двуязычный и который затрагивает не только конференцию, но и сообщество.

**Comment by binakot** [comment]
> Давайте возьмём какой-нибудь готовый? типа такого https://pitercss.com/code-of-conduct-ru

Их CoC под лицензией [CC BY 3.0](https://creativecommons.org/licenses/by/3.0/deed.ru). Его нужно будет соблюдать. К тому же у них почти полная копипаста http://2012.jsconf.us/#/about, плюс добавления антихарасмента из https://geekfeminism.wikia.org/wiki/Conference_anti-harassment/Policy

А чем тебе наш не нравится? Если есть какие-то дополнения, давайте его просто допишем.

**Comment by TyVik** [comment]
В /dev/null правила.
