### ISSUE TITLE
При запросе несуществующего события возвращать 204 NO CONTENT

### ISSUE THREAD

**Issue by binakot** [krddevdays/backend#90]
Связано с задачей https://github.com/krddevdays/frontend/issues/96

**Comment by langovoi** [comment]
Почему 204?

**Comment by binakot** [comment]
Потому что для этого придумали этот HTTP CODE. Но вообще в HTTP кодах такой ад, можно использовать любоей, какой нравится, хоть 200 OK с пустым телом. Главное, чтобы не 500. Фронт должен понимать, что это не ошибка, а штатная ситуация отсутствия данных. Если редирект сделать на 500-ую, то со стороны UX будет без разницы посыпался бэк или просто обратились к несуществующему ивенту.

**Comment by langovoi** [comment]
204 не для этого 🙃
500 на фронте падает, потому что где-то не обработал исключение.

**Comment by binakot** [comment]
204 NO CONTENT:  ```The server has successfully fulfilled the request and that there is no additional content to send in the response payload body.```.  Думаю, для нашего кейса более-менее подходит. С натяжкой, конечно. В целом, мне без разницы какой код будет. Главное, поведение реализовать.

**Comment by langovoi** [comment]
Так на клиентской стороне это нужно хендлить.

**Comment by binakot** [comment]
Окей. Наш бек проксирует запрос до QTickets. А при запросе несуществующего ивента или internal error server (когда QTickets просто сдох) мы их можем отличить? Чтобы явно фронту сказать, чувак с бэком все норм, просто ты запросил того, чего нет? У меня такой поинт. Нельзя на оба кейса просто кидать 500.

**Comment by langovoi** [comment]
Наш бекенд не проксирует запрос.
У нас собственная система событий, с возможностью регистрации через Qtickets.

Для получения информации о доступности регистрации (типы билетов и их стоимость) используется другое API.

Если этот запрос в Qtickets упадёт, то мы просто не покажем информацию по билетам на клиенте (https://github.com/krddevdays/frontend/blob/master/pages/events/%5Bid%5D/index.tsx#L473)

**Comment by binakot** [comment]
То есть мы на стороне фронта сейчас отличаем 500 error, когда посыпался бэк, и ошибку, когда запрошено несуществующее событие?

**Comment by langovoi** [comment]
Можем, но не делаем этого

**Comment by binakot** [comment]
@langovoi  Тогда к бэку тут нет вопросов? Задача чисто по фронту? Если да, то закрывай.

**Comment by langovoi** [comment]
Сделал на фронте
